
services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecurepassword
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: spring-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecurepassword
    
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "443:443"  # Expose HTTPS port
      - "80:80"    # Expose HTTP port for redirection
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the Nginx configuration
      - ./nginx.crt:/etc/nginx/ssl/nginx.crt  # Mount the SSL certificate
      - ./nginx.key:/etc/nginx/ssl/nginx.key  # Mount the SSL private key
    depends_on:
      - app  # Ensure Nginx starts after the Spring Boot app

volumes:
  postgres_data: