# Use an official JDK runtime as a parent image
FROM openjdk:21-jdk-slim
# Set working directory
WORKDIR /app

# Copy the application JAR file
COPY target/*.jar app.jar

# Expose port 8080
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]